Models/Corporate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaxWebApp.Data;

namespace TaxWebApp.Models
{
    public class Corporate
    {
        //ID for database
        public long Id { get; set; }

        //All Columns from Corporate excel sheet
        public static string LastNumber { get; set; }

        public string Type { get; set; }

        public string Number { get; set; }

        public string Name { get; set; }

        public string New { get; set; }

        public string In { get; set; }

        public string Notes { get; set; }

        public string Status { get; set; }

        public string Preparer { get; set; }

        public static Stack<string> AvailableNumbers = new Stack<string>();

        public static string getNextNumber(TaxDataContext contextDB)
        {

            if (AvailableNumbers.Count() > 0)
            {
                return AvailableNumbers.Pop();
            }

            //Get current People in DB, sorted by Number, pads the Number with 0's to make sure they are the same length when sorted
            Corporate[] corporateList = contextDB.Corporate.OrderBy(m => m.Number.PadLeft(contextDB.Corporate.Count(), '0')).ToArray();

            //Gets the last number that was used, doesn't check for missing numbers that were deleted by user
            string currentNumber = corporateList[(corporateList.Length - 1)].Number;

            //Increment the last Number entered by 1
            int lastNumber;
            Int32.TryParse(currentNumber, out lastNumber);
            lastNumber++;

            //updating the LastNumber, don't know why
            Corporate.LastNumber = lastNumber.ToString();

            //return next number
            return lastNumber.ToString();
        }
    }
}

Controllers/CorporatesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using TaxWebApp.Data;
using TaxWebApp.Models;

namespace TaxWebApp.Controllers
{
    public class CorporatesController : Controller
    {
        //DB STUFF
        private readonly TaxDataContext _contextDB;
        public CorporatesController(TaxDataContext context)
        {
            _contextDB = context;
        }

        public ActionResult Details(int id)
        {

            //Get current Corporates in DB
            Corporate Corporates = _contextDB.Corporate.Where(m => m.Id == id).FirstOrDefault();

            //Bringing current Corporates to details page
            ViewData["corporationById"] = Corporates;

            return View();
        }


        public async Task<IActionResult> Index(string sortOrder, string searchString, string searchString2, string currentFilter, int? page)
        {
            //set-up datetime
            DateTime dt = DateTime.Now;
            String date;
            date = dt.ToString("D", DateTimeFormatInfo.InvariantInfo);

            //Bringing date to the Home page
            ViewData["toDayDate"] = date;


            //Sorting and Search
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = sortOrder == "Name" ? "Name_desc" : "Name";
            ViewData["StatusSortParm"] = sortOrder == "Status" ? "Status_desc" : "Status";
            ViewData["PreparerSortParm"] = sortOrder == "Preparer" ? "Preparer_desc" : "Preparer";
            ViewData["NumberSortParm"] = sortOrder == "Number_desc" ? "Number" : "Number_desc";

            var corporates = from c in _contextDB.Corporate
                          select c;
            if (!String.IsNullOrEmpty(searchString))
            {
                corporates = corporates.Where(p => p.Number.Contains(searchString));

            }
            if (!String.IsNullOrEmpty(searchString2))
            {
                corporates = corporates.Where(x => x.Name.Contains(searchString2));

            }

            switch (sortOrder)
            {
                case "Name":
                    corporates = corporates.OrderBy(p => p.Name);
                    break;
                case "Name_desc":
                    corporates = corporates.OrderByDescending(p => p.Name);
                    break;
                case "Status":
                    corporates = corporates.OrderBy(p => p.Status);
                    break;
                case "Status_desc":
                    corporates = corporates.OrderByDescending(p => p.Status);
                    break;
                case "Preparer":
                    corporates = corporates.OrderBy(p => p.Preparer);
                    break;
                case "Preparer_desc":
                    corporates = corporates.OrderByDescending(p => p.Preparer);
                    break;
                case "Number":
                    corporates = corporates.OrderBy(p => p.Number);
                    break;
                case "Number_desc":
                    corporates = corporates.OrderByDescending(p => p.Number);
                    break;
                default:
                    corporates = corporates.OrderBy(p => p.Number);
                    break;
            }

            //Number of items on on page
            int pageSize = 30;
            int pageNumber = (page ?? 1);

            return View(await PaginatedList<Corporate>.CreateAsync(corporates.AsNoTracking(), page ?? 1, pageSize));
        }


        // GET: Person/Create
        public ActionResult Create()
        {
            DateTime dt = DateTime.Now;
            String date = dt.ToString("MM/dd/yyyy", DateTimeFormatInfo.InvariantInfo);

            //Bringing date to the Home page
            ViewData["toDayDate"] = date;


            return View();
        }

        // POST: Person/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Corporate newCorporation)
        {
            try
            {
                //Get the next Number
                string lastNum = Corporate.getNextNumber(_contextDB); ;
                Person.LastNumber = lastNum;

                Corporate.LastNumber = lastNum;

                newCorporation.Number = lastNum;

                // insert logic for adding a new corporate tax
                _contextDB.Add(newCorporation);
                _contextDB.SaveChanges();

                // returning the details page of the new corporate tax
                return RedirectToAction(nameof(Details), new { id = newCorporation.Id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Person/Edit/5
        public ActionResult Edit(long id)
        {
            //retrieve the corporate tax to edit
            Corporate corporate = _contextDB.Corporate.Where(m => m.Id == id).FirstOrDefault();

            //Bringing current Corporates to details page
            ViewData["corporationToEdit"] = corporate;

            return View();
        }

        // POST: Person/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(long id, Corporate editedCorporation)
        {
            if (editedCorporation == null)
            {
                throw new ArgumentNullException(nameof(editedCorporation));
            }

            try
            {
                // logic for updating an entry in the database
                Corporate corporation = _contextDB.Corporate.Where(m => m.Id == id).FirstOrDefault();
                corporation.Type = editedCorporation.Number;
                corporation.Number = editedCorporation.Number;
                corporation.Name = editedCorporation.Name;
                corporation.New = editedCorporation.New;
                corporation.In = editedCorporation.In;
                corporation.Notes = editedCorporation.Notes;
                corporation.Preparer = editedCorporation.Preparer;
                corporation.Status = editedCorporation.Status;
                _contextDB.SaveChanges();

                // returning the details page of the edited corporate tax
                return RedirectToAction(nameof(Details), new { id = id });
            }
            catch
            {
                return View();
            }
        }
        
        // GET: Person/Delete/5
        public ActionResult Delete(int id)
        {
            //retrieve the person with the given id to be removed 
            Corporate corporate = _contextDB.Corporate.Where(m => m.Id == id).FirstOrDefault();

            //Bringing current corparation to details page
            ViewData["corporateToDelete"] = corporate;

            return View();
        }

        // POST: Person/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                //retrieve the person with the given id to be removed 
                Corporate corporate = _contextDB.Corporate.Where(m => m.Id == id).FirstOrDefault();

                //save the number for re-use
                string number = corporate.Number;
                Corporate.AvailableNumbers.Push(number);

                //remove that person
                _contextDB.Corporate.Remove(corporate);
                _contextDB.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Corporates/Create.cshtml
@model TaxWebApp.Models.Corporate

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Corporate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>


            @*<div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>*@


            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="New" class="control-label"></label>
                <input asp-for="New" class="form-control" />
                <span asp-validation-for="New" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="In" class="control-label"></label>
                <input asp-for="In" class="form-control" value="@ViewData["toDayDate"]"/>
                <span asp-validation-for="In" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preparer" class="control-label"></label>
                <input asp-for="Preparer" class="form-control" />
                <span asp-validation-for="Preparer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-controller="Corporates" asp-action="Index">Back to List</a>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Corporates/Delete.cshtml
@model TaxWebApp.Models.Corporate

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Corporate corporate = (Corporate)ViewData["corporateToDelete"];
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Corporate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.New)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.New)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.In)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.In)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preparer)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Preparer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-controller="Corporates" asp-action="Index">Cancel</a>
    </form>
</div>

Views/Corporates/Details.cshtml
@model TaxWebApp.Models.Corporate

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Corporate corporate = (Corporate)ViewData["corporationById"];
}

<h2>Details</h2>

<div>
    <h4>Corporate</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Number)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.New)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.New)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.In)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.In)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preparer)
        </dt>
        <dd>
            @Html.DisplayFor(model => corporate.Preparer)
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@corporate.Id">Edit</a> |
    <a asp-action="Delete" asp-route-id="@corporate.Id">Delete</a> |
    <a asp-controller="Corporates" asp-action="Index">Back to List</a>
</div>

Views/Corporates/Edit.cshtml
@model TaxWebApp.Models.Corporate

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Corporate corporate = (Corporate)ViewData["corporationToEdit"];
}

<h2>Edit</h2>

<h4>Corporate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"  value="@corporate.Type" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" value="@corporate.Number" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" value="@corporate.Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="New" class="control-label"></label>
                <input asp-for="New" class="form-control" value="@corporate.New" />
                <span asp-validation-for="New" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="In" class="control-label"></label>
                <input asp-for="In" class="form-control" value="@corporate.In" />
                <span asp-validation-for="In" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" value="@corporate.Notes" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" value="@corporate.Status" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preparer" class="control-label"></label>
                <input asp-for="Preparer" class="form-control" value="@corporate.Preparer" />
                <span asp-validation-for="Preparer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Corporates" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Corporates/Index.cshtml
@model PaginatedList<TaxWebApp.Models.Corporate>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .table tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

<h1>Today is: @ViewData["toDayDate"] </h1>

<h2><b>Corporates</b></h2>
<p>
    <a href="/Corporates/Create/">Create New</a>
</p>


@using (Html.BeginForm())
{
    <p>
        Find by number: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)

        Find by name: @Html.TextBox("SearchString2", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<div>
    <table class="table" style="width:70%">
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NumberSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Number</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a>
            </th>
            <th>New</th>
            <th>Notes</th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PreparerSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Preparer</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["StatusSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Status</a>
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.New)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preparer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a href="/Corporates/Details/@item.Id">Details</a> |
                <a href="/Corporates/Edit/@item.Id">Edit</a>
            </td>
        </tr>
        }
    </table>
    <br />
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-page="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>
</div>